name: Build TWRP for Vivo PD2353

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib tox gcc-multilib libxml2-utils xsltproc zlib1g-dev python3 python3-pip git rsync
      - name: Config Git
        run: |
          git config --global user.name "qcopy"
          git config --global user.email "qcopy@example.com"
          git config --global --add safe.directory "*"
          git config --global credential.helper store
          git config --global http.postBuffer 524288000
      - name: Install Repo
        run: |
          mkdir -p ~/bin
          curl -L https://storage.googleapis.com/git-repo-downloads/repo -o ~/bin/repo
          chmod a+x ~/bin/repo
          head -n 1 ~/bin/repo | grep -E 'python(3)?' >/dev/null || (echo "Repo download failed!" && exit 1)
      - name: Initialize TWRP Manifest
        run: |
          mkdir -p ~/bin
          export PATH=~/bin:$PATH
          export PYTHONUNBUFFERED=1
          export GIT_TERMINAL_PROMPT=0
          mkdir twrp
          cd twrp
          python3 ~/bin/repo init --depth=1 --no-repo-verify -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
          
      - name: Sync TWRP Sources
        run: |
          export PATH=~/bin:$PATH
          export PYTHONUNBUFFERED=1
          export REPO_TRACE=1
          export GIT_TERMINAL_PROMPT=0
          export TERM=dumb
          cd twrp
          rm -rf prebuilts/rust
          python3 ~/bin/repo sync -c -j1 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune --fail-fast -v
      - name: Clone Device Tree
        run: |
          cd twrp
          rm -rf device/vivo/PD2353
          git clone --depth=1 ${{ github.server_url }}/${{ github.repository }} tmp_pd2353
          mkdir -p device/vivo
          mv -f tmp_pd2353/device/vivo/PD2353 device/vivo/PD2353
          rm -rf tmp_pd2353

      - name: Build TWRP
        run: |
          export PATH=~/bin:$PATH
          cd twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_PD2353-eng || (echo "Lunch failed!" && exit 1)
          mka recoveryimage -j$(nproc --all)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Vivo-PD2353
          path: |
            twrp/out/target/product/PD2353/recovery.img
            twrp/out/target/product/PD2353/boot.img
            twrp/out/target/product/PD2353/*.zip